package mapping;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JU.USERINFO.ID
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JU.USERINFO.USERNAME
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JU.USERINFO.PASSWORD
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JU.USERINFO.AGE
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    private Long age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JU.USERINFO.ID
     *
     * @return the value of JU.USERINFO.ID
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JU.USERINFO.ID
     *
     * @param id the value for JU.USERINFO.ID
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JU.USERINFO.USERNAME
     *
     * @return the value of JU.USERINFO.USERNAME
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JU.USERINFO.USERNAME
     *
     * @param username the value for JU.USERINFO.USERNAME
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JU.USERINFO.PASSWORD
     *
     * @return the value of JU.USERINFO.PASSWORD
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JU.USERINFO.PASSWORD
     *
     * @param password the value for JU.USERINFO.PASSWORD
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JU.USERINFO.AGE
     *
     * @return the value of JU.USERINFO.AGE
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public Long getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JU.USERINFO.AGE
     *
     * @param age the value for JU.USERINFO.AGE
     *
     * @mbg.generated Fri Jan 26 20:58:23 CST 2018
     */
    public void setAge(Long age) {
        this.age = age;
    }
}