package mapping;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.age
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.age
     *
     * @return the value of userinfo.age
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.age
     *
     * @param age the value for userinfo.age
     *
     * @mbg.generated Fri Jan 26 20:24:40 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}